### ISSUE TITLE
Chains of async functions

### ISSUE THREAD

**Issue by piranha** [WebReflection/wru#8]
Hey! I use wru for a long time now, mostly for my (rather small) open source projects and I love it!

Recently I ran into a case where I couldn't wrangle it into what's necessary. My problem right now is that I use JS which reacts to events asynchronously (using promises inside). Which means if I emulate click on a button, I have to wait for a little bit to check for reaction. 

It wasn't hard with wru.async until I got to the point where I want to do three clicks in succession. So here am I thinking about using Promise here — this would allow me to write a chain with delays inside. So I have this function:

```
    window.delay = (t) => new Promise(resolve => setTimeout(resolve, t, true));
```

which generates a Promise, and I'm using it like this:

```
    test1(el => {
      wru.async(_ => {
        delay(1)
          .then(_ => click(el.$('a')))
          .then(_ => delay(16))
          .then(_ => wru.assert(el.$('a').innerText, el.$('a').innerText == 'Updated!'))
      })();
    });
```

This actually gives me result which looks like this:

![image](https://user-images.githubusercontent.com/6553/123275942-6e7e6380-d50d-11eb-9461-67f89daee766.png)

So 1 assert has passed successfully. Why is there the other one, which failed? I wonder if I'm doing something wrong here. Hopefully my explanation is clear, if not — please ask me, I will elaborate. If you want it to see in action (no promise stuff yet though), look here: https://kasta-ua.github.io/twinspark-js/

**Comment by WebReflection** [comment]
You are not returning the promise ... 

```js
test1(el => {
      wru.async(_ =>
        delay(1)
          .then(_ => click(el.$('a')))
          .then(_ => delay(16))
          .then(_ => wru.assert(el.$('a').innerText, el.$('a').innerText == 'Updated!'))
      )();
    });
```

would this work? ... sorry but last activities in this project span from 10 to 5 years ago, I am not using `wru` anymore, and probably I should just deprecate it, as I'm not planning to maintain it further.

**Comment by piranha** [comment]
Returning promise does not help... Looking at code I'm not sure why it should, though.

Eh, I know it's not updated much, but it worked so well all that time. :-)

**Comment by piranha** [comment]
I just wrote it in a nested callbacks-way, and it works, so I guess I don't really need this, it just would be nice. But between me not understanding why it fails and you not really touching this I guess this will never be done.

Maybe the right way is to close the issue so it won't nag you? :)

**Comment by WebReflection** [comment]
Will do, and archive + deprecate this module. Glad you solved though 👍
